# @package _global_

defaults:
  - _self_
  - data: mnist # choose datamodule with `test_dataloader()` for evaluation
  - model: mnist
  - logger: null
  - trainer: default
  - paths: default
  - extras: default
  - hydra: default

task_name: "eval"

tags: ["dev"]

# when True, run Trainer.predict and save outputs instead of Trainer.test
predict: False

# passing checkpoint path is necessary for evaluation or prediction
ckpt_path: ???
